## Préambule
site_name: mon_site
site_description: Un site sur quelque chose.
site_author: mon_nom
site_favicon: "img/favicon.ico" 

theme: 
  name: readthedocs # mkdocs

## Architecture
nav:
  - Accueil: index.md
  - Guide:
    - Pense-bête: pense_bete.md

## Extensions
markdown_extensions:
  - toc:
      permalink: true # false
      baselevel: 1 # 2
